#!/usr/bin/env bash

#rsync -avz -e 'ssh -p 2607' /home/rab/Projects/MeteorRadar/src pi@92.29.114.226:/home/pi/source/MeteorRadar

#rsync -avz --remove-source-files -e 'ssh -p 2607' pi@92.29.114.226:/home/pi/radar_data ~
#find ~/radar_data/ -name '*.npz' -mtime -1 | sort

# Copy the software to the pi
rsync -avz /home/rab/Projects/MeteorRadar/src pi@raspberrypi32:/home/pi/source/MeteorRadar

# Get the radar detection data from the pi
rsync -avz --remove-source-files --exclude Logs/ pi@raspberrypi32:/home/pi/radar_data/* ~/radar_data
rsync -avz pi@raspberrypi32:/home/pi/radar_data/Logs ~/radar_data/

# find ~/radar_data/ -name '*.npz' -mtime -1 | sort

# Clean up junk data older than 30 days, audio files older than 10 days
find ~/radar_data/Junk/ -type f -mtime +40 -exec rm -f {} +
find ~/radar_data/Junk/ -name 'AUD*.raw' -type f -mtime +10 -exec rm -f {} +
